### ISSUE TITLE
-R affichage nom de dossier vide

### ISSUE THREAD

**Issue by Gawise** [Gawise/ft_ls#41]
"ft_ls -R" sur un dossier vide affiche le nom du dossier suivi de ":\n"
le vrai ls n'affiche rien

Ex:
➜  ft_ls git:(master) ✗ ./ft_ls -R bla
bla:
➜  ft_ls git:(master) ✗ ls -R bla
➜  ft_ls git:(master) ✗

**Comment by Akkud** [comment]
Résolu sauf erreur/oubli de ma part
