### ISSUE TITLE
Affichage du nom de dossier par erreur lors du -R

### ISSUE THREAD

**Issue by Akkud** [Gawise/ft_ls#46]
Il ne faut jamais afficher le nom du premier dossier meme quand il est passé en parametres
------------------
➜  ft_ls git:(pOl) ✗ ls -1R
Makefile
ft_ls

➜  ft_ls git:(pOl) ✗ ./ft_ls -1R
.:
Makefile
ft_ls

**Comment by Gawise** [comment]
Duplicate of #41

**Comment by Gawise** [comment]
J'ai ajouté un paramètre à ft_ls() pour savoir si c'est le premier dossier qu'on print
