### ISSUE TITLE
Le tri a besoin d'etre case sensitive en cas de temps equivalent avec -t

### ISSUE THREAD

**Issue by Akkud** [Gawise/ft_ls#47]
➜  ft_ls git:(pOl) ✗ ls -tl
total 112
-rwxr-xr-x   1 pacharbo  2018_paris  52132 Aug 19 18:41 ft_ls
drwxr-xr-x   9 pacharbo  2018_paris    306 Aug 19 18:41 libft
drwxr-xr-x  15 pacharbo  2018_paris    510 Aug 19 18:40 obj
drwxr-xr-x  14 pacharbo  2018_paris    476 Aug 19 18:38 src
-rw-r--r--   1 pacharbo  2018_paris    761 Aug 18 19:18 **Makefile**
drwxr-xr-x   3 pacharbo  2018_paris    102 Aug 18 19:18 **includes**
-rw-r--r--   1 pacharbo  2018_paris      0 Dec 10  2013 **B**
-rw-r--r--   1 pacharbo  2018_paris      0 Dec 10  2013 **a**
-rw-r--r--   1 pacharbo  2018_paris      0 Dec 10  2013 **c**
➜  ft_ls git:(pOl) ✗ ./ft_ls -tl
total 112
-rwxr-xr-x   1 pacharbo  2018_paris  52132 Aug 19 18:41 ft_ls
drwxr-xr-x   9 pacharbo  2018_paris    306 Aug 19 18:41 libft
drwxr-xr-x  15 pacharbo  2018_paris    510 Aug 19 18:40 obj
drwxr-xr-x  14 pacharbo  2018_paris    476 Aug 19 18:38 src
drwxr-xr-x   3 pacharbo  2018_paris    102 Aug 18 19:18 **includes**
-rw-r--r--   1 pacharbo  2018_paris    761 Aug 18 19:18 **Makefile**
-rw-r--r--   1 pacharbo  2018_paris      0 Dec 10  2013 **a**
-rw-r--r--   1 pacharbo  2018_paris      0 Dec 10  2013 **B**
-rw-r--r--   1 pacharbo  2018_paris      0 Dec 10  2013 **c**

Pourtant le tri sur le -l est bel et bien case sensitive

**Comment by Gawise** [comment]
On faisait pas le tri sur le nom si le flag -t était donné
