### ISSUE TITLE
affichage de la ligne total a tort avec -l et un fichier en parametre

### ISSUE THREAD

**Issue by Akkud** [Gawise/ft_ls#49]
➜  tests git:(pOl) ✗ ls -l aaa
-rw-r--r--  1 pacharbo  2018_paris  0 Aug 19 19:41 aaa
➜  tests git:(pOl) ✗ ../ft_ls -l aaa
total 0
-rw-r--r--  1 pacharbo  2018_paris  0 Aug 19 19:41 aaa

**Comment by Gawise** [comment]
T'as essayé de débattre avec lui pour le convaincre ?

**Comment by Akkud** [comment]
Les accents sont chiants a mettre en qwerty, merci de ta compréhension

**Comment by Akkud** [comment]
Résolu
